#!/bin/bash

# Prompt user for WayNotif installation.
while true; do

    if [ ! -f $HOME/waynotif ]; then
       read -p "Do you want to install WayNotif? (Y/n) " yn
    else
       read -p "Do you want to reinstall WayNotif? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) WAYNOTIF=true && break;;
         [Nn]* ) WAYNOTIF=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid Unsuspend icon installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/unsuspend-waydroid.desktop ]; then
       read -p "Do you want to install Waydroid Unsuspend? (Y/n) " yn
    else
       read -p "Do you want to reinstall Waydroid Unsuspend? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) UNSUSPEND=true && break;;
         [Nn]* ) UNSUSPEND=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid Suspend icon installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/suspend-waydroid.desktop ]; then
       read -p "Do you want to install Waydroid Suspend? (Y/n) " yn
    else
       read -p "Do you want to reinstall Waydroid Suspend? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) SUSPEND=true && break;;
         [Nn]* ) SUSPEND=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid optimizations.
while true; do
       read -p "Do want to install Waydroid optimizations? (Y/n) " yn
    case $yn in
         [Yy]* ) OPTIMIZE=true && break;;
         [Nn]* ) OPTIMIZE=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for htop installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/htop.desktop ]; then
       read -p "Do you want to install htop? (Intended for Ubuntu Touch) (Y/n) " yn
    else
       read -p "Do you want to reinstall htop? (Intended for Ubuntu Touch) (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) HTOP=true && break;;
         [Nn]* ) HTOP=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for bashtop installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/bashtop.desktop ]; then
       read -p "Do you want to install bashtop? (Intended for Ubuntu Touch) (Y/n) " yn
    else
       read -p "Do you want to reinstall bashtop? (Intended for Ubuntu Touch) (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) BASHTOP=true && break;;
         [Nn]* ) BASHTOP=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for ncdu installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/ncdu.desktop ]; then
       read -p "Do you want to install ncdu? (Intended for Ubuntu Touch) (Y/n) " yn
    else
       read -p "Do you want to reinstall ncdu? (Intended for Ubuntu Touch) (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) NCDU=true && break;;
         [Nn]* ) NCDU=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for libertine shell icon installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/libertine.desktop ]; then
       read -p "Do you want to install libertine shell icon? (Intended for Ubuntu Touch) (Y/n) " yn
    else
       read -p "Do you want to reinstall liberitne shell icon? (Intended for Ubuntu Touch) (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) LIBERTINE=true && break;;
         [Nn]* ) LIBERTINE=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

if [ "$WAYNOTIF" == "true" ] || [ "$SUSPEND" == "true" ] || [ "$UNSUSPEND" == "true" ] || [ "$OPTIMIZE" == "true" ]; then

   # Check whether or not Waydroid is installed.
   if [ $(LANG=C type waydroid 2>/dev/null | wc -l) = 1 ]; then
      true
   else
      echo "Waydroid is not installed"
      exit 1
   fi

   # Check whether or not Waydroid is initialized.
   if [ ! -f /var/lib/waydroid/images/system.img ]; then
      echo "Waydroid is not initialized. Run waydroid init."
      exit 1
   fi

   # Check whether or not Waydroid or even started in the first place.
   if waydroid status | grep STOPPED; then
      echo "Waydroid is not running"
      exit 1
   fi
fi

# WayNotif installation.
if [ "$WAYNOTIF" == "true" ]; then
   echo "Installing WayNotif..."
   curl https://raw.githubusercontent.com/BardiaMGTGC/WayNotif/main/waynotif --output $HOME/waynotif &> /dev/null
   chmod +x $HOME/waynotif
   if [ -d $HOME/.cache/waynotif ]; then
      rm -rf $HOME/.cache/waynotif/notifications*
   fi
   echo "WayNotif installed successfully."
fi

# Waydroid Unsuspend installation.
if [ "$UNSUSPEND" == "true" ]; then
   echo "Installing Waydroid Unsuspend..."
   wget https://bardia.tech/unsuspend-waydroid.desktop --output-document=$HOME/.local/share/applications/unsuspend-waydroid.desktop &> /dev/null
   echo "Waydroid Unsuspend installed successfulyl"
fi

# Waydroid Suspend installation.
if [ "$SUSPEND" == "true" ]; then
   echo "Installing Waydroid Suspend..."
   wget https://bardia.tech/suspend-waydroid.desktop --output-document=$HOME/.local/share/applications/suspend-waydroid.desktop &> /dev/null
   echo "Waydorid Suspend installed successfully."
fi

# htop installation.
if [ "$HTOP" == "true" ]; then
   echo "Installing htop..."

   if [ ! -d $HOME/.cache ]; then
      mkdir -p $HOME/.cache
   fi

   if [ ! -d $HOME/.local/share/icons ]; then
      mkdir -p $HOME/.local/share/icons
   fi

   wget https://github.com/tuxecure/crackle/releases/latest/download/crackle.zip --output-document=$HOME/.cache/crackle.zip &> /dev/null
   unzip $HOME/.cache/crackle.zip -d $HOME/.cache/crackle &> /dev/null
   cd $HOME/.cache
   crackle/crackle setup &> /dev/null
   source $HOME/.bashrc
   rm -rf $HOME/.cache/crackle
   crackle install htop &> /dev/null
   wget https://bardia.tech/htop.desktop --output-document=$HOME/.local/share/applications/htop.desktop &> /dev/null
   wget https://bardia.tech/htop.png --output-document=$HOME/.local/share/icons/htop.png &> /dev/null
   echo "htop installed successfully."
fi

# bashtop installation.
if [ "$BASHTOP" == "true" ]; then
   echo "Installing bashtop..."

   if [ ! -d $HOME/.cache ]; then
      mkdir -p $HOME/.cache
   fi

   if [ ! -d $HOME/.local/share/icons ]; then
      mkdir -p $HOME/.local/share/icons
   fi

   wget https://github.com/tuxecure/crackle/releases/latest/download/crackle.zip --output-document=$HOME/.cache/crackle.zip &> /dev/null
   unzip $HOME/.cache/crackle.zip -d $HOME/.cache/crackle &> /dev/null
   cd $HOME/.cache
   crackle/crackle setup &> /dev/null
   source $HOME/.bashrc
   rm -rf $HOME/.cache/crackle
   crackle install bash bashtop &> /dev/null
   wget https://bardia.tech/bashtop.desktop --output-document=$HOME/.local/share/applications/bashtop.desktop &> /dev/null
   wget https://bardia.tech/bashtop.png --output-document=$HOME/.local/share/icons/bashtop.png &> /dev/null
   if cat $(which bashtop) | grep "#!/bin/bash"; then
      awk '{gsub("#!/bin/bash, "#!/home/phablet/.local/bin/bash");print}' $(which bashtop) > $HOME/.cache/bashtop
      mv $HOME/.cache/bashtop $(which bashtop)
   fi
   echo "bashtop installed successfully."
fi

# ncdu installation.
if [ "$NCDU" == "true" ]; then
   echo "Installing ncdu..."

   if [ ! -d $HOME/.cache ]; then
      mkdir -p $HOME/.cache
   fi

   if [ ! -d $HOME/.local/share/icons ]; then
      mkdir -p $HOME/.local/share/icons
   fi

   https://github.com/tuxecure/crackle/releases/latest/download/crackle.zip --output-document=$HOME/.cache/crackle.zip &> /dev/null
   unzip $HOME/.cache/crackle.zip -d $HOME/.cache/crackle &> /dev/null
   cd $HOME/.cache
   crackle/crackle setup &> /dev/null
   source $HOME/.bashrc
   rm -rf $HOME/.cache/crackle
   crackle install ncdu &> /dev/null
   wget https://bardia.tech/ncdu.desktop --output-document=$HOME/.local/share/applications/ncdu.desktop &> /dev/null
   wget https://bardia.tech/ncdu.png --output-document=$HOME/.local/share/icons/ncdu.png &> /dev/null
   echo "ncdu installed successfully."
fi

# Libertine shell icon installation.
if [ "$LIBERTINE" == "true" ]; then
   echo "Installing libertine shell icon..."

   if [ ! -d $HOME/.local/bin ]; then
      mkdir -p $HOME/.local/bin
   fi

   wget https://bardia.tech/libertine.desktop --output-document=$HOME/.local/share/applications/libertine.desktop &> /dev/null
   wget https://bardia.tech/lish --output-document=$HOME/.local/bin/lish &> /dev/null
   chmod +x $HOME/.local/bin/lish
   echo "Libertine shell icon installed successfully."
fi

# Check if anything was installed first if they were then add user to sudoers so that script can use Waydroid command without a password.
if [ "$SUSPEND" == "false" ] && [ "$UNSUSPEND" == "false" ] && [ "$WAYNOTIF" == "false" ]; then
   echo "Did not add sudoers entries."
elif sudo cat /etc/sudoers | grep waydroid; then
   echo "Did not add sudoers entries."
else
   echo "Adding needed entries to sudoers."
   # Save username of current user to a file so that it can be used later.
   whoami > /tmp/whoami
   if [ "$USER" == "phablet" ]; then
      sudo mount -o remount,rw /
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/usr/bin/waydroid" >> /etc/sudoers'
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/bin/mount" >> /etc/sudoers'
      sudo mount -o remount,ro /
      rm -f /tmp/whoami
      echo "Waydroid and mount have been added to sudoers."
   else
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/usr/bin/waydroid" >> /etc/sudoers'
      rm -f /tmp/whoami
      echo "Waydroid has been added to sudoers."
   fi
fi

# Enable adb over network so that unsuspend icon can use it.
if [ "$UNSUSPEND" == "true" ]; then
   echo setprop service.adb.tcp.port 5555 | sudo waydroid shell
   echo stop adbd | sudo waydroid shell
   echo start adbd | sudo waydroid shell
fi

# Enable adb over network so that suspend icon can use it.
if [ "$SUSPEND" == "true" ]; then
   echo setprop service.adb.tcp.port 5555 | sudo waydroid shell
   echo stop adbd | sudo waydroid shell
   echo start adbd | sudo waydroid shell
fi

# Apply Waydroid optimizations.
if [ "$OPTIMIZE" == "true" ]; then
   waydroid prop set persist.waydroid.suspend true
   waydroid prop set ro.config.low_ram true
   echo "Waydroid optimizations have been applied."
fi
