#!/bin/bash

# Check whether or not Waydroid is installed.
if [ $(LANG=C type waydroid 2>/dev/null | wc -l) = 1 ]; then
   true
else
   echo "Waydroid is not installed"
   exit 1
fi

# Check whether or not Waydroid is initialized.
if [ ! -f /var/lib/waydroid/images/system.img ]; then
   echo "Waydroid is not initialized. Run waydroid init."
   exit 1
fi

# Check whether or not Waydroid or even started in the first place.
if waydroid status | grep STOPPED; then
   echo "Waydroid is not running"
   exit 1
fi

# Prompt user for WayNotif installation.
while true; do

    if [ ! -f $HOME/waynotif ]; then
       read -p "Do you want to install WayNotif? (Y/n) " yn
    else
       read -p "Do you want to reinstall WayNotif? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) WAYNOTIF=true && break;;
         [Nn]* ) WAYNOTIF=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid Unsuspend icon installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/unsuspend-waydroid.desktop ]; then
       read -p "Do you want to install Waydroid Unsuspend? (Y/n) " yn
    else
       read -p "Do you want to reinstall Waydroid Unsuspend? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) UNSUSPEND=true && break;;
         [Nn]* ) UNSUSPEND=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid Suspend icon installation.
while true; do

    if [ ! -f $HOME/.local/share/applications/suspend-waydroid.desktop ]; then
       read -p "Do you want to install Waydroid Suspend? (Y/n) " yn
    else
       read -p "Do you want to reinstall Waydroid Suspend? (Y/n) " yn
    fi

    case $yn in
         [Yy]* ) SUSPEND=true && break;;
         [Nn]* ) SUSPEND=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# Prompt user for Waydroid optimizations.
while true; do
       read -p "Do want to install Waydroid optimizations? (Y/n) " yn
    case $yn in
         [Yy]* ) OPTIMIZE=true && break;;
         [Nn]* ) OPTIMIZE=false && break;;
         * ) echo "Please answer Y(es) or N(o).";;
    esac

done

# WayNotif installation.
if [ "$WAYNOTIF" == "true" ]; then
   echo "Installing WayNotif..."
   curl https://raw.githubusercontent.com/BardiaMGTGC/WayNotif/main/waynotif --output $HOME/waynotif &> /dev/null
   chmod +x $HOME/waynotif
   if [ -d $HOME/.cache/waynotif ]; then
      rm -rf $HOME/.cache/waynotif/notifications*
   fi
fi

# Waydroid Unsuspend installation.
if [ "$UNSUSPEND" == "true" ]; then
   echo "Installing Waydroid Unsuspend..."
   wget https://bardia.tech/unsuspend-waydroid.desktop --output-document=$HOME/.local/share/applications/unsuspend-waydroid.desktop &> /dev/null
fi

# Waydroid Suspend installation.
if [ "$SUSPEND" == "true" ]; then
   echo "Installing Waydroid Suspend..."
   wget https://bardia.tech/suspend-waydroid.desktop --output-document=$HOME/.local/share/applications/suspend-waydroid.desktop &> /dev/null
fi

# Check if anything was installed first if they were then add user to sudoers so that script can use Waydroid command without a password.
if [ "$SUSPEND" == "false" ] && [ "$UNSUSPEND" == "false" ] && [ "$WAYNOTIF" == "false" ]; then
   echo "Did not add sudoers entries."
elif sudo cat /etc/sudoers | grep waydroid; then
   echo "Did not add sudoers entries."
else
   echo "Adding needed entries to sudoers."
   # Save username of current user to a file so that it can be used later.
   whoami > /tmp/whoami
   if [ "$USER" == "phablet" ]; then
      sudo mount -o remount,rw /
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/usr/bin/waydroid" >> /etc/sudoers'
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/bin/mount" >> /etc/sudoers'
      sudo mount -o remount,ro /
      rm -f /tmp/whoami
   else
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/usr/bin/waydroid" >> /etc/sudoers'
      sudo su -c 'export WHOAMI=$(cat /tmp/whoami) && echo "$WHOAMI ALL=(ALL) NOPASSWD:/bin/mount" >> /etc/sudoers'
      rm -f /tmp/whoami
   fi
fi

# Enable adb over network so that unsuspend icon can use it.
if [ "$UNSUSPEND" == "true" ]; then
   echo setprop service.adb.tcp.port 5555 | sudo waydroid shell
   echo stop adbd | sudo waydroid shell
   echo start adbd | sudo waydroid shell
fi

# Enable adb over network so that suspend icon can use it.
if [ "$SUSPEND" == "true" ]; then
   echo setprop service.adb.tcp.port 5555 | sudo waydroid shell
   echo stop adbd | sudo waydroid shell
   echo start adbd | sudo waydroid shell
fi

# Apply Waydroid optimizations.
if [ "$OPTIMIZE" == "true" ]; then
   waydroid prop set persist.waydroid.suspend true
   waydroid prop set ro.config.low_ram true
fi
